"""
Seeds MongoDB food collection with diverse food items.

Handles:
- Dietary & allergen tagging
- OpenAI vector embeddings for semantic search
- Rich AI metadata (mood, occasion, taste, texture)
- Creates vector search index for food items
"""

import asyncio
import json
from datetime import datetime, timezone
import os
from pymongo import AsyncMongoClient
from pymongo.operations import SearchIndexModel
from openai import AsyncOpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

MONGO_URI = os.getenv("MONGODB_URL")
DB_NAME = os.getenv("DATABASE_NAME", "vybe")
FOOD_COLLECTION = "food"

# OpenAI configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIMENSIONS = 1536

# Comprehensive food database for all 21 restaurants
FOOD_ITEMS_BY_RESTAURANT = {
    "restaurant_1": [  # 24hr Vegan Diner
        {"name": "Midnight Vegan Burger", "description": "Juicy plant-based patty with fresh lettuce, tomato, and vegan aioli on toasted bun", "category": "main_course", "cuisine": ["vegan", "american"], "dietary": ["vegan"], "allergens": [], "ingredients": ["plant-based patty", "lettuce", "tomato", "vegan mayo"], "spice_level": 1, "preparation_method": ["grilled"], "meal_types": ["lunch", "dinner", "late night"], "price": 11.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["satisfying", "hearty"], "occasion": ["late night", "quick meal"], "taste_profile": ["savory", "fresh"], "texture": ["crispy", "soft"]}},
        {"name": "Crispy Tofu Fries", "description": "Golden fried tofu cubes with sea salt and sriracha mayo for dipping", "category": "appetizer", "cuisine": ["vegan", "asian"], "dietary": ["vegan"], "allergens": ["soy"], "ingredients": ["tofu", "cornstarch", "sriracha", "vegan mayo"], "spice_level": 2, "preparation_method": ["fried"], "meal_types": ["snack", "appetizer"], "price": 6.99, "calories": 280, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.5, "ai_metadata": {"mood": ["fun", "crispy"], "occasion": ["snack", "side dish"], "taste_profile": ["savory", "spicy"], "texture": ["crispy", "soft"]}},
        {"name": "Vegan Dumplings (6pc)", "description": "Hand-folded dumplings filled with cabbage, mushroom, and ginger with soy dipping sauce", "category": "appetizer", "cuisine": ["vegan", "asian"], "dietary": ["vegan"], "allergens": ["soy", "sesame"], "ingredients": ["dumpling wrapper", "cabbage", "mushroom", "ginger", "soy sauce"], "spice_level": 1, "prep_time_minutes": 20, "preparation_method": ["steamed", "pan-fried"], "meal_types": ["appetizer", "snack"], "price": 7.50, "calories": 180, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["comforting", "classic"], "occasion": ["appetizer", "snack"], "taste_profile": ["savory", "ginger-forward"], "texture": ["chewy", "tender"]}},
        {"name": "24-Hour Buddha Noodle Soup", "description": "Warm ramen broth with tofu, bok choy, mushrooms, and soft noodles in a deeply flavored miso broth", "category": "main_course", "cuisine": ["vegan", "asian"], "dietary": ["vegan"], "allergens": ["soy", "sesame"], "ingredients": ["ramen noodles", "miso broth", "tofu", "bok choy", "mushrooms"], "spice_level": 2, "preparation_method": ["simmered"], "meal_types": ["lunch", "dinner", "late night"], "price": 10.99, "calories": 380, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["warming", "comforting"], "occasion": ["late night", "cold weather"], "taste_profile": ["umami", "savory"], "texture": ["chewy", "tender"]}},
        {"name": "Midnight Pad Thai", "description": "Stir-fried rice noodles with tofu, peanuts, lime, and tamarind sauce served piping hot", "category": "main_course", "cuisine": ["vegan", "thai"], "dietary": ["vegan"], "allergens": ["peanuts", "soy"], "ingredients": ["rice noodles", "tofu", "peanuts", "tamarind", "lime"], "spice_level": 3, "preparation_method": ["stir-fried"], "meal_types": ["dinner", "late night"], "price": 11.50, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.6, "ai_metadata": {"mood": ["flavorful", "aromatic"], "occasion": ["dinner", "late night"], "taste_profile": ["sweet", "tangy", "nutty", "spicy"], "texture": ["chewy", "crunchy"]}},
        {"name": "Creamy Coconut Curry", "description": "Chickpeas and vegetables simmered in rich coconut curry with jasmine rice", "category": "main_course", "cuisine": ["vegan", "thai"], "dietary": ["vegan"], "allergens": ["coconut"], "ingredients": ["chickpeas", "coconut milk", "curry spices", "vegetables", "jasmine rice"], "spice_level": 2, "preparation_method": ["simmered"], "meal_types": ["dinner"], "price": 12.99, "calories": 450, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["warming", "comforting"], "occasion": ["dinner"], "taste_profile": ["creamy", "spicy", "aromatic"], "texture": ["soft", "tender"]}},
    ],
    "restaurant_2": [  # Vegan Kitchen (Korean-inspired)
        {"name": "Crispy Vegan Fried Chicken", "description": "Golden-brown plant-based fried chicken served with gochujang mayo and kimchi slaw", "category": "main_course", "cuisine": ["korean", "vegan"], "dietary": ["vegan"], "allergens": [], "ingredients": ["plant-based chicken", "gochujang", "kimchi", "vegan mayo"], "spice_level": 3, "preparation_method": ["fried"], "meal_types": ["lunch", "dinner"], "price": 13.99, "calories": 480, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["indulgent", "crispy", "savory"], "occasion": ["casual lunch", "street food"], "taste_profile": ["spicy", "savory", "umami"], "texture": ["crispy", "juicy"]}},
        {"name": "Kimchi Corn Dogs", "description": "Vegan hot dogs coated in panko and corn batter, fried golden, served with kimchi relish and gochujang ketchup", "category": "main_course", "cuisine": ["korean", "vegan"], "dietary": ["vegan"], "allergens": [], "ingredients": ["plant-based sausage", "corn batter", "panko", "kimchi", "gochujang"], "spice_level": 2, "preparation_method": ["fried"], "meal_types": ["lunch", "dinner", "snack"], "price": 8.99, "calories": 320, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["fun", "street-style"], "occasion": ["quick bite", "snack"], "taste_profile": ["savory", "spicy"], "texture": ["crispy", "crunchy"]}},
        {"name": "Korean Dumpling Platter (8pc)", "description": "Pan-fried and steamed Korean mandu with vegetables and tofu, served with soy-ginger dipping sauce", "category": "appetizer", "cuisine": ["korean", "vegan"], "dietary": ["vegan"], "allergens": ["soy", "sesame"], "ingredients": ["dumpling wrapper", "tofu", "vegetables", "soy sauce", "ginger"], "spice_level": 1, "prep_time_minutes": 15, "preparation_method": ["pan-fried", "steamed"], "meal_types": ["appetizer", "snack"], "price": 9.99, "calories": 220, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["savory", "comforting"], "occasion": ["appetizer"], "taste_profile": ["savory", "umami"], "texture": ["chewy", "tender"]}},
        {"name": "Tteokbokki (Korean Rice Cakes)", "description": "Chewy rice cakes in spicy gochujang sauce with vegetables and vegan cheese topping", "category": "main_course", "cuisine": ["korean", "vegan"], "dietary": ["vegan"], "allergens": ["soy"], "ingredients": ["rice cakes", "gochujang", "vegetables", "vegan cheese"], "spice_level": 4, "preparation_method": ["simmered"], "meal_types": ["lunch", "dinner", "snack"], "price": 9.50, "calories": 350, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.6, "ai_metadata": {"mood": ["spicy", "chewy"], "occasion": ["snack", "comfort food"], "taste_profile": ["spicy", "savory", "sweet"], "texture": ["chewy", "soft"]}},
        {"name": "Kimbap (Korean Sushi Roll)", "description": "Rolled sushi-style with pickled vegetables, tofu, and sesame oil in seasoned rice", "category": "main_course", "cuisine": ["korean", "vegan"], "dietary": ["vegan"], "allergens": ["sesame", "soy"], "ingredients": ["sushi rice", "nori", "pickled vegetables", "tofu", "sesame oil"], "spice_level": 1, "prep_time_minutes": 15, "preparation_method": ["assembled"], "meal_types": ["lunch", "dinner"], "price": 10.99, "calories": 380, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["light", "fresh"], "occasion": ["lunch", "quick meal"], "taste_profile": ["savory", "nutty", "umami"], "texture": ["chewy", "crunchy"]}},
        {"name": "Vegan Korean Fried Rice", "description": "Fluffy jasmine rice stir-fried with mixed vegetables, tofu, soy sauce, and topped with vegan fried egg", "category": "main_course", "cuisine": ["korean", "vegan"], "dietary": ["vegan"], "allergens": ["soy"], "ingredients": ["jasmine rice", "vegetables", "tofu", "soy sauce", "sesame oil"], "spice_level": 1, "preparation_method": ["stir-fried"], "meal_types": ["lunch", "dinner"], "price": 11.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.6, "ai_metadata": {"mood": ["satisfying", "comforting"], "occasion": ["lunch", "dinner"], "taste_profile": ["savory", "umami"], "texture": ["fluffy", "tender"]}},
    ],
    "restaurant_3": [  # Purely Vegan Hub
        {"name": "House Special Vegan Platter", "description": "Chef's selection of rotating vegan specialties featuring seasonal vegetables and plant-based proteins", "category": "main_course", "cuisine": ["vegan"], "dietary": ["vegan"], "allergens": [], "ingredients": ["seasonal vegetables", "plant-based proteins"], "spice_level": 1, "preparation_method": ["roasted", "sautéed"], "meal_types": ["lunch", "dinner"], "price": 14.99, "calories": 500, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["special", "chef-curated"], "occasion": ["dinner"], "taste_profile": ["seasonal", "fresh", "balanced"], "texture": ["varied"]}},
        {"name": "Vegan Wellington", "description": "Layered mushroom duxelles wrapped in puff pastry with herb filling and red wine reduction", "category": "main_course", "cuisine": ["vegan", "british"], "dietary": ["vegan"], "allergens": ["nuts"], "ingredients": ["mushrooms", "puff pastry", "herbs", "nuts", "wine"], "spice_level": 0, "prep_time_minutes": 30, "preparation_method": ["baked"], "meal_types": ["dinner"], "price": 16.99, "calories": 520, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": True, "is_popular": False, "rating": 4.8, "ai_metadata": {"mood": ["elegant", "impressive"], "occasion": ["special occasion", "fine dining"], "taste_profile": ["umami", "earthy"], "texture": ["flaky", "tender"]}},
        {"name": "Rainbow Buddha Salad", "description": "Mixed greens with roasted vegetables, quinoa, chickpeas, nuts, and tahini dressing", "category": "main_course", "cuisine": ["vegan"], "dietary": ["vegan"], "allergens": ["sesame", "nuts"], "ingredients": ["mixed greens", "roasted vegetables", "quinoa", "chickpeas", "tahini"], "spice_level": 0, "preparation_method": ["raw", "roasted"], "meal_types": ["lunch", "dinner"], "price": 12.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["healthy", "light"], "occasion": ["lunch", "wellness"], "taste_profile": ["fresh", "nutty", "earthy"], "texture": ["crunchy", "creamy"]}},
        {"name": "Creamy Cashew Pasta", "description": "Handmade vegan pasta in a silky cashew cream sauce with garlic, lemon, and fresh herbs", "category": "main_course", "cuisine": ["vegan", "italian"], "dietary": ["vegan"], "allergens": ["nuts"], "ingredients": ["pasta", "cashews", "garlic", "lemon", "herbs"], "spice_level": 0, "prep_time_minutes": 20, "preparation_method": ["boiled", "simmered"], "meal_types": ["lunch", "dinner"], "price": 13.99, "calories": 480, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["indulgent", "creamy"], "occasion": ["dinner"], "taste_profile": ["creamy", "savory", "herby"], "texture": ["soft", "creamy"]}},
    ],
    "restaurant_4": [  # The Green Leaf Bistro (Vegetarian Italian)
        {"name": "Eggplant Parmesan", "description": "Crispy breaded eggplant layers with marinara sauce and melted mozzarella", "category": "main_course", "cuisine": ["italian", "vegetarian"], "dietary": ["vegetarian"], "allergens": ["dairy", "gluten"], "ingredients": ["eggplant", "breadcrumbs", "mozzarella", "marinara", "basil"], "spice_level": 1, "preparation_method": ["fried", "baked"], "meal_types": ["lunch", "dinner"], "price": 13.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["comforting", "indulgent"], "occasion": ["dinner"], "taste_profile": ["savory", "rich"], "texture": ["crispy", "creamy"]}},
        {"name": "Caprese Salad", "description": "Fresh mozzarella, tomatoes, and basil with balsamic reduction and olive oil", "category": "appetizer", "cuisine": ["italian", "vegetarian"], "dietary": ["vegetarian"], "allergens": ["dairy"], "ingredients": ["mozzarella", "tomatoes", "basil", "balsamic vinegar", "olive oil"], "spice_level": 0, "preparation_method": ["assembled"], "meal_types": ["appetizer", "lunch"], "price": 10.99, "calories": 280, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["fresh", "light"], "occasion": ["appetizer", "lunch"], "taste_profile": ["fresh", "tangy", "savory"], "texture": ["soft", "crunchy"]}},
        {"name": "Pappardelle with Mushroom Ragù", "description": "Wide ribbon pasta with slow-cooked mushroom, walnut, and tomato sauce", "category": "main_course", "cuisine": ["italian", "vegetarian"], "dietary": ["vegetarian"], "allergens": ["gluten", "nuts"], "ingredients": ["pappardelle pasta", "mushrooms", "walnuts", "tomatoes", "garlic"], "spice_level": 0, "prep_time_minutes": 30, "preparation_method": ["simmered"], "meal_types": ["lunch", "dinner"], "price": 14.99, "calories": 480, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["hearty", "comforting"], "occasion": ["dinner"], "taste_profile": ["earthy", "savory", "umami"], "texture": ["tender", "soft"]}},
    ],
    "restaurant_5": [  # Standard Grill & Bar
        {"name": "New York Strip Steak", "description": "Prime cut steak grilled to perfection, served with garlic mashed potatoes and seasonal vegetables", "category": "main_course", "cuisine": ["american", "steakhouse"], "dietary": ["regular"], "allergens": ["dairy"], "ingredients": ["strip steak", "butter", "garlic", "potatoes", "vegetables"], "spice_level": 1, "preparation_method": ["grilled"], "meal_types": ["dinner"], "price": 28.99, "calories": 620, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["indulgent", "classic"], "occasion": ["dinner", "special occasion"], "taste_profile": ["savory", "rich", "meaty"], "texture": ["tender", "juicy"]}},
        {"name": "Crispy Fried Chicken Wings (12pc)", "description": "Golden-fried chicken wings tossed in buffalo sauce, served with ranch dip and celery sticks", "category": "appetizer", "cuisine": ["american"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["chicken wings", "flour", "buffalo sauce", "ranch dip"], "spice_level": 3, "preparation_method": ["fried"], "meal_types": ["appetizer", "snack"], "price": 12.99, "calories": 480, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["spicy", "crispy", "indulgent"], "occasion": ["appetizer", "snack"], "taste_profile": ["spicy", "savory", "tangy"], "texture": ["crispy", "juicy"]}},
        {"name": "Classic Cheeseburger", "description": "Char-grilled beef patty with melted cheddar, bacon, lettuce, tomato, and special sauce on a toasted bun", "category": "main_course", "cuisine": ["american"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["beef", "cheddar", "bacon", "lettuce", "tomato"], "spice_level": 1, "preparation_method": ["grilled"], "meal_types": ["lunch", "dinner"], "price": 14.99, "calories": 520, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["satisfying", "classic"], "occasion": ["lunch", "casual dinner"], "taste_profile": ["savory", "rich", "meaty"], "texture": ["juicy", "crispy"]}},
    ],
    "restaurant_6": [  # Sultan's Halal Kitchen
        {"name": "Chicken Shawarma", "description": "Tender marinated chicken carved from a vertical spit, wrapped in pita with tahini sauce and pickled vegetables", "category": "main_course", "cuisine": ["middle eastern", "halal"], "dietary": ["halal"], "allergens": ["sesame", "gluten"], "ingredients": ["chicken", "pita", "tahini", "tomatoes", "onions"], "spice_level": 2, "prep_time_minutes": 25, "preparation_method": ["roasted"], "meal_types": ["lunch", "dinner"], "price": 12.99, "calories": 520, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["savory", "aromatic"], "occasion": ["lunch", "dinner"], "taste_profile": ["spiced", "savory", "tangy"], "texture": ["tender", "soft"]}},
        {"name": "Lamb Mandy", "description": "Slow-cooked lamb with yellow rice, topped with goat yogurt sauce and fresh herbs", "category": "main_course", "cuisine": ["middle eastern", "halal"], "dietary": ["halal"], "allergens": ["dairy"], "ingredients": ["lamb", "rice", "yogurt", "spices", "herbs"], "spice_level": 2, "prep_time_minutes": 45, "preparation_method": ["slow-cooked"], "meal_types": ["lunch", "dinner"], "price": 15.99, "calories": 580, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["aromatic", "warming"], "occasion": ["dinner"], "taste_profile": ["spiced", "tender", "savory"], "texture": ["tender", "fluffy"]}},
        {"name": "Falafel Platter", "description": "Golden-fried chickpea balls with hummus, tahini, salad, and pita bread", "category": "main_course", "cuisine": ["middle eastern"], "dietary": ["halal"], "allergens": ["sesame", "gluten"], "ingredients": ["chickpeas", "falafel spices", "hummus", "tahini", "pita"], "spice_level": 1, "preparation_method": ["fried"], "meal_types": ["lunch", "dinner"], "price": 10.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.6, "ai_metadata": {"mood": ["flavorful", "satisfying"], "occasion": ["lunch", "dinner"], "taste_profile": ["spiced", "nutty", "savory"], "texture": ["crispy", "creamy"]}},
    ],
    "restaurant_7": [  # The Kosher Deli
        {"name": "Classic Pastrami Sandwich", "description": "Succulent house-cured and smoked pastrami piled high on rye bread with spicy brown mustard and pickles", "category": "main_course", "cuisine": ["jewish", "deli"], "dietary": ["kosher"], "allergens": ["gluten"], "ingredients": ["pastrami", "rye bread", "mustard", "pickles"], "spice_level": 1, "prep_time_minutes": 15, "preparation_method": ["steamed"], "meal_types": ["lunch", "brunch"], "price": 13.99, "calories": 520, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["classic", "nostalgic"], "occasion": ["lunch", "brunch"], "taste_profile": ["savory", "smoky", "tangy"], "texture": ["tender", "juicy"]}},
        {"name": "Matzah Ball Soup", "description": "Light fluffy matzah balls in a deeply flavored chicken broth with vegetables and dill", "category": "main_course", "cuisine": ["jewish", "deli"], "dietary": ["kosher"], "allergens": [], "ingredients": ["matzah meal", "eggs", "chicken broth", "vegetables", "dill"], "spice_level": 0, "prep_time_minutes": 45, "preparation_method": ["simmered"], "meal_types": ["lunch", "brunch", "dinner"], "price": 10.99, "calories": 280, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["comforting", "nostalgic"], "occasion": ["brunch", "lunch"], "taste_profile": ["savory", "light", "herby"], "texture": ["soft", "fluffy"]}},
    ],
    "restaurant_8": [  # Sky & Stars Rooftop Lounge
        {"name": "Pan-Seared Calamari", "description": "Tender squid rings flash-fried until golden, tossed with lemon, garlic, and parsley", "category": "appetizer", "cuisine": ["contemporary", "mediterranean"], "dietary": ["regular"], "allergens": ["seafood", "gluten"], "ingredients": ["calamari", "lemon", "garlic", "parsley"], "spice_level": 1, "preparation_method": ["fried"], "meal_types": ["appetizer", "dinner"], "price": 14.99, "calories": 280, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["elegant", "light"], "occasion": ["appetizer", "special dinner"], "taste_profile": ["savory", "citrus", "herbaceous"], "texture": ["tender", "crispy"]}},
        {"name": "Roasted Duck Breast", "description": "Pan-seared duck breast with cherry gastrique, served with truffle mashed potatoes and microgreens", "category": "main_course", "cuisine": ["contemporary", "fine dining"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["duck", "cherries", "potatoes", "truffle oil", "microgreens"], "spice_level": 1, "prep_time_minutes": 30, "preparation_method": ["roasted", "pan-seared"], "meal_types": ["dinner"], "price": 24.99, "calories": 580, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["elegant", "sophisticated"], "occasion": ["special dinner", "date night"], "taste_profile": ["rich", "fruity", "savory"], "texture": ["tender", "crispy"]}},
        {"name": "Ceviche with Plantain Chips", "description": "Fresh fish cured in citrus juice with avocado, cilantro, and served with crispy plantain chips", "category": "appetizer", "cuisine": ["contemporary", "latin"], "dietary": ["regular"], "allergens": ["seafood"], "ingredients": ["fish", "lime", "avocado", "cilantro", "plantains"], "spice_level": 1, "prep_time_minutes": 20, "preparation_method": ["raw", "cured"], "meal_types": ["appetizer", "dinner"], "price": 13.99, "calories": 320, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["light", "fresh"], "occasion": ["appetizer"], "taste_profile": ["citrus", "fresh", "spicy"], "texture": ["tender", "crunchy"]}},
    ],
    "restaurant_9": [  # The Cozy Study Cafe
        {"name": "Artisan Cappuccino", "description": "Double espresso with velvety steamed milk and latte art", "category": "beverage", "cuisine": ["cafe"], "dietary": ["vegetarian"], "allergens": ["dairy"], "ingredients": ["espresso", "steamed milk"], "spice_level": 0, "prep_time_minutes": 3, "preparation_method": ["espresso machine"], "meal_types": ["breakfast", "brunch"], "price": 4.50, "calories": 120, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["energizing", "comforting"], "occasion": ["breakfast", "study"], "taste_profile": ["rich", "creamy", "bitter"], "texture": ["creamy", "smooth"]}},
        {"name": "Croissant with Jam", "description": "Buttery French croissant with homemade jam and whipped butter", "category": "breakfast", "cuisine": ["cafe", "french"], "dietary": ["vegetarian"], "allergens": ["dairy", "gluten", "eggs"], "ingredients": ["butter", "flour", "jam", "eggs"], "spice_level": 0, "preparation_method": ["baked"], "meal_types": ["breakfast", "brunch"], "price": 5.99, "calories": 320, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["indulgent", "cozy"], "occasion": ["breakfast", "brunch"], "taste_profile": ["buttery", "sweet", "light"], "texture": ["flaky", "tender"]}},
        {"name": "Avocado Toast on Sourdough", "description": "Mashed avocado on toasted sourdough with lemon juice, sea salt, and microgreens", "category": "breakfast", "cuisine": ["cafe"], "dietary": ["vegetarian", "vegan"], "allergens": ["gluten"], "ingredients": ["avocado", "sourdough", "lemon", "microgreens"], "spice_level": 0, "preparation_method": ["toasted", "assembled"], "meal_types": ["breakfast", "brunch", "lunch"], "price": 8.99, "calories": 280, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.6, "ai_metadata": {"mood": ["fresh", "healthy"], "occasion": ["breakfast", "brunch"], "taste_profile": ["creamy", "fresh", "tangy"], "texture": ["creamy", "crunchy"]}},
    ],
    "restaurant_10": [  # Sunday Brunch House
        {"name": "Classic Eggs Benedict", "description": "Poached eggs on English muffin with Canadian bacon and silky hollandaise sauce", "category": "main_course", "cuisine": ["brunch", "american"], "dietary": ["vegetarian"], "allergens": ["dairy", "eggs", "gluten"], "ingredients": ["eggs", "english muffin", "bacon", "hollandaise"], "spice_level": 0, "prep_time_minutes": 15, "preparation_method": ["poached"], "meal_types": ["brunch", "lunch"], "price": 12.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["indulgent", "classic"], "occasion": ["brunch", "weekend"], "taste_profile": ["rich", "creamy", "savory"], "texture": ["soft", "tender"]}},
        {"name": "Fluffy Pancakes with Berries", "description": "Stack of fluffy pancakes topped with whipped cream, maple syrup, and fresh mixed berries", "category": "main_course", "cuisine": ["brunch", "american"], "dietary": ["vegetarian"], "allergens": ["dairy", "eggs", "gluten"], "ingredients": ["flour", "eggs", "milk", "berries", "maple syrup"], "spice_level": 0, "prep_time_minutes": 15, "preparation_method": ["grilled"], "meal_types": ["breakfast", "brunch"], "price": 13.99, "calories": 520, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["sweet", "indulgent"], "occasion": ["brunch", "breakfast"], "taste_profile": ["sweet", "fruity"], "texture": ["fluffy", "soft"]}},
        {"name": "Vegetable Quiche", "description": "Silky egg custard tart filled with roasted vegetables, cheese, and fresh herbs", "category": "main_course", "cuisine": ["brunch"], "dietary": ["vegetarian"], "allergens": ["dairy", "eggs", "gluten"], "ingredients": ["eggs", "cream", "vegetables", "cheese", "pie crust"], "spice_level": 0, "prep_time_minutes": 45, "preparation_method": ["baked"], "meal_types": ["brunch", "lunch"], "price": 11.99, "calories": 380, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["savory", "elegant"], "occasion": ["brunch"], "taste_profile": ["savory", "creamy"], "texture": ["tender", "fluffy"]}},
    ],
    "restaurant_11": [  # Spice & Rhythm Indian Kitchen
        {"name": "Butter Chicken Curry", "description": "Tender chicken in a creamy tomato sauce with spices, served with basmati rice and naan", "category": "main_course", "cuisine": ["indian"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["chicken", "tomatoes", "cream", "spices", "rice", "naan"], "spice_level": 2, "prep_time_minutes": 30, "preparation_method": ["simmered"], "meal_types": ["lunch", "dinner"], "price": 14.99, "calories": 520, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["aromatic", "creamy", "warming"], "occasion": ["dinner"], "taste_profile": ["spiced", "creamy", "savory"], "texture": ["tender", "soft"]}},
        {"name": "Tandoori Chicken", "description": "Marinated chicken roasted in a clay oven, served with basmati rice and cucumber raita", "category": "main_course", "cuisine": ["indian"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["chicken", "yogurt", "spices", "rice", "cucumber"], "spice_level": 3, "prep_time_minutes": 45, "preparation_method": ["tandoor-roasted"], "meal_types": ["lunch", "dinner"], "price": 15.99, "calories": 480, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["aromatic", "smoky"], "occasion": ["dinner"], "taste_profile": ["spiced", "smoky", "savory"], "texture": ["tender", "charred"]}},
        {"name": "Chickpea Curry (Chana Masala)", "description": "Spiced chickpeas and tomatoes with warming spices, served with basmati rice and bread", "category": "main_course", "cuisine": ["indian"], "dietary": ["vegetarian"], "allergens": ["gluten"], "ingredients": ["chickpeas", "tomatoes", "spices", "rice", "bread"], "spice_level": 2, "preparation_method": ["simmered"], "meal_types": ["lunch", "dinner"], "price": 11.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["warming", "spiced"], "occasion": ["lunch", "dinner"], "taste_profile": ["spiced", "savory", "tangy"], "texture": ["soft", "tender"]}},
        {"name": "Samosas (3pc)", "description": "Crispy pastry triangles filled with spiced potato and peas, served with tamarind chutney", "category": "appetizer", "cuisine": ["indian"], "dietary": ["vegetarian"], "allergens": ["gluten", "dairy"], "ingredients": ["potato", "peas", "spices", "pastry", "tamarind"], "spice_level": 2, "preparation_method": ["fried"], "meal_types": ["appetizer", "snack"], "price": 6.99, "calories": 240, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.6, "ai_metadata": {"mood": ["crispy", "spiced"], "occasion": ["appetizer", "snack"], "taste_profile": ["spiced", "savory"], "texture": ["crispy", "soft"]}},
    ],
    "restaurant_12": [  # The Night Owl Diner
        {"name": "Classic Cheeseburger & Fries", "description": "Juicy beef patty with melted American cheese, lettuce, tomato, and special sauce, served with crispy fries", "category": "main_course", "cuisine": ["american", "comfort food"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["beef", "cheese", "lettuce", "tomato", "potatoes"], "spice_level": 1, "preparation_method": ["grilled"], "meal_types": ["lunch", "dinner", "late night"], "price": 11.99, "calories": 580, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["classic", "satisfying"], "occasion": ["late night", "casual meal"], "taste_profile": ["savory", "rich", "meaty"], "texture": ["juicy", "crispy"]}},
        {"name": "Crispy Fried Chicken Tenders & Milkshake", "description": "Golden-fried chicken strips with a creamy milkshake in vanilla, chocolate, or strawberry", "category": "main_course", "cuisine": ["american", "comfort food"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["chicken", "flour", "milk", "ice cream"], "spice_level": 0, "preparation_method": ["fried"], "meal_types": ["lunch", "dinner", "late night"], "price": 12.99, "calories": 620, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["indulgent", "nostalgic"], "occasion": ["late night", "snack"], "taste_profile": ["savory", "sweet", "creamy"], "texture": ["crispy", "creamy"]}},
        {"name": "Apple Pie with Ice Cream", "description": "Warm homemade apple pie with flaky crust, topped with vanilla ice cream", "category": "dessert", "cuisine": ["american", "dessert"], "dietary": ["vegetarian"], "allergens": ["dairy", "gluten", "eggs"], "ingredients": ["apples", "flour", "butter", "ice cream"], "spice_level": 0, "prep_time_minutes": 45, "preparation_method": ["baked"], "meal_types": ["dessert"], "price": 6.99, "calories": 380, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["sweet", "comforting"], "occasion": ["dessert", "late night"], "taste_profile": ["sweet", "spiced", "fruity"], "texture": ["flaky", "creamy"]}},
    ],
    "restaurant_13": [  # Green Garden Bistro
        {"name": "Jackfruit Tacos", "description": "Pulled jackfruit with chipotle aioli, cabbage slaw, and avocado in corn tortillas", "category": "main_course", "cuisine": ["vegan", "mexican"], "dietary": ["vegan"], "allergens": [], "ingredients": ["jackfruit", "chipotle", "cabbage", "avocado", "tortillas"], "spice_level": 2, "prep_time_minutes": 15, "preparation_method": ["pulled", "assembled"], "meal_types": ["lunch", "dinner"], "price": 12.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["adventurous", "fresh"], "occasion": ["lunch", "dinner"], "taste_profile": ["spicy", "tangy", "savory"], "texture": ["tender", "crispy"]}},
        {"name": "Cauliflower Steak", "description": "Thick-cut cauliflower steak roasted until golden, topped with tahini sauce and pomegranate seeds", "category": "main_course", "cuisine": ["vegan", "contemporary"], "dietary": ["vegan"], "allergens": ["sesame"], "ingredients": ["cauliflower", "tahini", "pomegranate", "herbs"], "spice_level": 1, "preparation_method": ["roasted"], "meal_types": ["lunch", "dinner"], "price": 14.99, "calories": 320, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["elegant", "healthy"], "occasion": ["dinner"], "taste_profile": ["savory", "nutty", "sweet"], "texture": ["tender", "crispy"]}},
    ],
    "restaurant_14": [  # Family Feast Pizzeria
        {"name": "Margherita Pizza", "description": "Traditional pizza with San Marzano tomatoes, fresh mozzarella, basil, and olive oil", "category": "main_course", "cuisine": ["italian", "pizza"], "dietary": ["vegetarian"], "allergens": ["dairy", "gluten"], "ingredients": ["pizza dough", "tomatoes", "mozzarella", "basil", "olive oil"], "spice_level": 0, "prep_time_minutes": 20, "preparation_method": ["wood-fired"], "meal_types": ["lunch", "dinner"], "price": 13.99, "calories": 480, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["classic", "comforting"], "occasion": ["family dinner"], "taste_profile": ["savory", "herby", "fresh"], "texture": ["crispy", "chewy"]}},
        {"name": "Pepperoni Pizza", "description": "Classic pizza topped with tomato sauce, mozzarella, and crispy pepperoni", "category": "main_course", "cuisine": ["italian", "pizza"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["pizza dough", "tomato sauce", "mozzarella", "pepperoni"], "spice_level": 1, "prep_time_minutes": 20, "preparation_method": ["wood-fired"], "meal_types": ["lunch", "dinner"], "price": 14.99, "calories": 520, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["comforting", "classic"], "occasion": ["family dinner"], "taste_profile": ["savory", "meaty", "cheesy"], "texture": ["crispy", "chewy"]}},
        {"name": "Lasagna", "description": "Layered pasta with meat ragu, béchamel sauce, and melted mozzarella", "category": "main_course", "cuisine": ["italian"], "dietary": ["regular"], "allergens": ["dairy", "gluten", "eggs"], "ingredients": ["lasagna noodles", "ground meat", "tomato sauce", "béchamel", "mozzarella"], "spice_level": 1, "prep_time_minutes": 45, "preparation_method": ["baked"], "meal_types": ["lunch", "dinner"], "price": 14.99, "calories": 580, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["hearty", "comforting"], "occasion": ["family dinner"], "taste_profile": ["savory", "rich", "meaty"], "texture": ["soft", "tender"]}},
    ],
    "restaurant_15": [  # The Sushi Master
        {"name": "Omakase Experience (Chef's Selection)", "description": "Curated selection of premium nigiri sushi featuring the finest catches of the day", "category": "main_course", "cuisine": ["japanese", "sushi"], "dietary": ["regular"], "allergens": ["seafood", "soy"], "ingredients": ["premium fish", "sushi rice", "soy sauce", "wasabi"], "spice_level": 1, "prep_time_minutes": 30, "preparation_method": ["assembled"], "meal_types": ["dinner"], "price": 65.00, "calories": 320, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 5.0, "ai_metadata": {"mood": ["elegant", "refined"], "occasion": ["special occasion", "fine dining"], "taste_profile": ["fresh", "subtle", "umami"], "texture": ["tender", "chewy"]}},
        {"name": "Spicy Tuna Roll", "description": "Fresh tuna mixed with spicy mayo wrapped in rice and nori, sliced into bite-sized pieces", "category": "main_course", "cuisine": ["japanese", "sushi"], "dietary": ["regular"], "allergens": ["seafood", "soy"], "ingredients": ["tuna", "spicy mayo", "sushi rice", "nori"], "spice_level": 3, "prep_time_minutes": 15, "preparation_method": ["rolled"], "meal_types": ["lunch", "dinner"], "price": 12.99, "calories": 280, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["spicy", "fresh"], "occasion": ["lunch", "dinner"], "taste_profile": ["spicy", "fresh", "savory"], "texture": ["chewy", "crunchy"]}},
        {"name": "California Roll", "description": "Imitation crab, avocado, and cucumber rolled with rice and nori", "category": "main_course", "cuisine": ["japanese", "sushi"], "dietary": ["regular"], "allergens": ["seafood", "soy"], "ingredients": ["imitation crab", "avocado", "cucumber", "sushi rice", "nori"], "spice_level": 0, "prep_time_minutes": 10, "preparation_method": ["rolled"], "meal_types": ["lunch", "dinner"], "price": 10.99, "calories": 240, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.6, "ai_metadata": {"mood": ["fresh", "mild"], "occasion": ["lunch", "dinner"], "taste_profile": ["fresh", "mild", "sweet"], "texture": ["chewy", "crunchy"]}},
    ],
    "restaurant_16": [  # Street Tacos Express
        {"name": "Al Pastor Tacos (3pc)", "description": "Marinated pork cooked on a vertical spit, served in soft tortillas with pineapple, onions, and cilantro", "category": "main_course", "cuisine": ["mexican", "street food"], "dietary": ["regular"], "allergens": ["gluten"], "ingredients": ["pork", "pineapple", "tortillas", "onions", "cilantro"], "spice_level": 2, "prep_time_minutes": 15, "preparation_method": ["roasted"], "meal_types": ["lunch", "dinner"], "price": 9.99, "calories": 380, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["flavorful", "street-style"], "occasion": ["lunch", "quick meal"], "taste_profile": ["spiced", "fruity", "savory"], "texture": ["tender", "juicy"]}},
        {"name": "Carnitas Tacos (3pc)", "description": "Slow-cooked pulled pork with crispy edges served in corn tortillas with cilantro and lime", "category": "main_course", "cuisine": ["mexican", "street food"], "dietary": ["regular"], "allergens": [], "ingredients": ["pork", "corn tortillas", "cilantro", "lime"], "spice_level": 1, "prep_time_minutes": 10, "preparation_method": ["slow-cooked"], "meal_types": ["lunch", "dinner"], "price": 9.99, "calories": 420, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["satisfying", "savory"], "occasion": ["lunch", "dinner"], "taste_profile": ["savory", "rich", "tangy"], "texture": ["tender", "crispy"]}},
    ],
    "restaurant_17": [  # The Gluten-Free Haven
        {"name": "Gluten-Free Pizza Margherita", "description": "Delicious gluten-free pizza crust topped with tomato, mozzarella, and fresh basil", "category": "main_course", "cuisine": ["gluten free", "pizza"], "dietary": ["gluten free"], "allergens": ["dairy"], "ingredients": ["gluten-free crust", "tomatoes", "mozzarella", "basil"], "spice_level": 0, "prep_time_minutes": 20, "preparation_method": ["baked"], "meal_types": ["lunch", "dinner"], "price": 13.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["comforting", "safe"], "occasion": ["lunch", "dinner"], "taste_profile": ["savory", "fresh"], "texture": ["crispy", "chewy"]}},
        {"name": "Gluten-Free Chocolate Cake", "description": "Rich chocolate cake made with gluten-free flour, served with fresh whipped cream", "category": "dessert", "cuisine": ["gluten free", "dessert"], "dietary": ["gluten free"], "allergens": ["dairy", "eggs"], "ingredients": ["gluten-free flour", "chocolate", "eggs", "butter", "cream"], "spice_level": 0, "prep_time_minutes": 30, "preparation_method": ["baked"], "meal_types": ["dessert"], "price": 7.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["indulgent", "safe"], "occasion": ["dessert"], "taste_profile": ["sweet", "rich", "chocolatey"], "texture": ["soft", "moist"]}},
        {"name": "Gluten-Free Bread with Butter", "description": "Freshly baked gluten-free bread with creamy butter", "category": "appetizer", "cuisine": ["gluten free", "bakery"], "dietary": ["gluten free"], "allergens": ["dairy", "eggs"], "ingredients": ["gluten-free flour", "butter", "eggs"], "spice_level": 0, "preparation_method": ["baked"], "meal_types": ["breakfast", "snack"], "price": 4.99, "calories": 280, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.6, "ai_metadata": {"mood": ["comforting", "safe"], "occasion": ["breakfast", "snack"], "taste_profile": ["savory", "buttery"], "texture": ["fluffy", "soft"]}},
    ],
    "restaurant_18": [  # The Jazz Corner Bar & Grill
        {"name": "Seared Scallops with Caviar", "description": "Pan-seared scallops topped with caviar and lemon foam, served over microgreens", "category": "appetizer", "cuisine": ["contemporary", "seafood"], "dietary": ["regular"], "allergens": ["seafood", "dairy"], "ingredients": ["scallops", "caviar", "lemon", "microgreens"], "spice_level": 0, "prep_time_minutes": 15, "preparation_method": ["pan-seared"], "meal_types": ["appetizer", "dinner"], "price": 18.99, "calories": 240, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["elegant", "luxurious"], "occasion": ["special dinner"], "taste_profile": ["savory", "umami", "briny"], "texture": ["tender", "soft"]}},
        {"name": "Jazz Chord Cocktail", "description": "Signature cocktail with bourbon, ginger liqueur, and fresh lemon", "category": "beverage", "cuisine": ["contemporary", "cocktails"], "dietary": ["regular"], "allergens": [], "ingredients": ["bourbon", "ginger liqueur", "lemon", "bitters"], "spice_level": 1, "prep_time_minutes": 5, "preparation_method": ["mixed"], "meal_types": ["dinner", "late night"], "price": 12.99, "calories": 150, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": True, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["sophisticated", "warming"], "occasion": ["cocktail hour"], "taste_profile": ["spiced", "citrus", "warming"], "texture": ["smooth", "aromatic"]}},
    ],
    "restaurant_19": [  # Bubble Tea Paradise
        {"name": "Classic Taro Bubble Tea", "description": "Smooth taro milk tea with chewy tapioca pearls and optional boba", "category": "beverage", "cuisine": ["bubble tea"], "dietary": ["vegetarian"], "allergens": ["dairy"], "ingredients": ["taro powder", "milk tea", "tapioca pearls"], "spice_level": 0, "prep_time_minutes": 5, "preparation_method": ["mixed", "shaken"], "meal_types": ["snack", "afternoon"], "price": 5.99, "calories": 220, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["sweet", "fun"], "occasion": ["afternoon snack"], "taste_profile": ["sweet", "creamy"], "texture": ["chewy", "smooth"]}},
        {"name": "Mango Passion Fruit Tea", "description": "Refreshing blend of mango and passion fruit with popping boba", "category": "beverage", "cuisine": ["bubble tea"], "dietary": ["vegan"], "allergens": [], "ingredients": ["mango", "passion fruit", "tea", "popping boba"], "spice_level": 0, "prep_time_minutes": 5, "preparation_method": ["mixed", "shaken"], "meal_types": ["snack", "afternoon"], "price": 6.49, "calories": 200, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": True, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["tropical", "refreshing"], "occasion": ["afternoon snack"], "taste_profile": ["tropical", "sweet", "tangy"], "texture": ["chewy", "smooth"]}},
        {"name": "Brown Sugar Bubble Tea", "description": "Rich brown sugar milk tea with chewy tapioca pearls", "category": "beverage", "cuisine": ["bubble tea"], "dietary": ["vegetarian"], "allergens": ["dairy"], "ingredients": ["brown sugar", "milk tea", "tapioca pearls"], "spice_level": 0, "prep_time_minutes": 5, "preparation_method": ["mixed", "shaken"], "meal_types": ["snack", "afternoon"], "price": 5.99, "calories": 240, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["sweet", "comforting"], "occasion": ["afternoon snack"], "taste_profile": ["sweet", "creamy"], "texture": ["chewy", "smooth"]}},
    ],
    "restaurant_20": [  # The Steakhouse Prime
        {"name": "USDA Prime Ribeye (16oz)", "description": "Perfectly marbled ribeye steak, grilled to medium-rare, served with truffle butter and seasonal vegetables", "category": "main_course", "cuisine": ["steakhouse", "fine dining"], "dietary": ["regular"], "allergens": ["dairy"], "ingredients": ["ribeye steak", "truffle butter", "vegetables"], "spice_level": 1, "prep_time_minutes": 30, "preparation_method": ["grilled"], "meal_types": ["dinner"], "price": 48.99, "calories": 680, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": True, "is_popular": True, "rating": 5.0, "ai_metadata": {"mood": ["indulgent", "premium"], "occasion": ["special dinner", "celebration"], "taste_profile": ["rich", "savory", "meaty"], "texture": ["tender", "juicy"]}},
        {"name": "Caviar Appetizer with Toast", "description": "Premium caviar served with crusty toast points and crème fraîche", "category": "appetizer", "cuisine": ["steakhouse", "luxury"], "dietary": ["regular"], "allergens": ["dairy", "gluten"], "ingredients": ["caviar", "toast", "crème fraîche"], "spice_level": 0, "prep_time_minutes": 5, "preparation_method": ["assembled"], "meal_types": ["appetizer"], "price": 24.99, "calories": 180, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["luxurious", "elegant"], "occasion": ["special occasion"], "taste_profile": ["briny", "umami", "buttery"], "texture": ["creamy", "crunchy"]}},
        {"name": "Lobster Tail with Drawn Butter", "description": "Fresh cold-water lobster tail broiled and served with drawn butter", "category": "main_course", "cuisine": ["steakhouse", "seafood"], "dietary": ["regular"], "allergens": ["seafood", "dairy"], "ingredients": ["lobster tail", "butter", "lemon"], "spice_level": 0, "prep_time_minutes": 20, "preparation_method": ["broiled"], "meal_types": ["dinner"], "price": 34.99, "calories": 420, "vegetarian_friendly": False, "vegan_friendly": False, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.9, "ai_metadata": {"mood": ["luxurious", "elegant"], "occasion": ["special dinner"], "taste_profile": ["sweet", "buttery", "umami"], "texture": ["tender", "juicy"]}},
    ],
    "restaurant_21": [  # Tropical Smoothie Bowl Café
        {"name": "Açaí Energy Bowl", "description": "Açaí base with granola, coconut, fresh berries, and almonds topped with honey drizzle", "category": "breakfast", "cuisine": ["healthy", "bowls"], "dietary": ["vegan"], "allergens": ["nuts", "coconut"], "ingredients": ["acai", "granola", "coconut", "berries", "almonds", "honey"], "spice_level": 0, "prep_time_minutes": 5, "preparation_method": ["assembled"], "meal_types": ["breakfast", "brunch"], "price": 10.99, "calories": 420, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": False, "is_signature_dish": True, "is_popular": True, "rating": 4.8, "ai_metadata": {"mood": ["energizing", "fresh"], "occasion": ["breakfast", "post-workout"], "taste_profile": ["sweet", "fruity", "crunchy"], "texture": ["creamy", "crunchy"]}},
        {"name": "Tropical Mango Smoothie", "description": "Blended mango, coconut milk, and banana with fresh pineapple juice", "category": "beverage", "cuisine": ["healthy", "smoothies"], "dietary": ["vegan"], "allergens": ["coconut"], "ingredients": ["mango", "coconut milk", "banana", "pineapple"], "spice_level": 0, "prep_time_minutes": 3, "preparation_method": ["blended"], "meal_types": ["breakfast", "snack"], "price": 7.99, "calories": 280, "vegetarian_friendly": True, "vegan_friendly": True, "gluten_free": True, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["tropical", "refreshing"], "occasion": ["breakfast", "snack"], "taste_profile": ["sweet", "tropical"], "texture": ["creamy", "smooth"]}},
        {"name": "Protein Power Bowl", "description": "Vanilla yogurt base with granola, berries, protein powder, and almond butter", "category": "breakfast", "cuisine": ["healthy", "bowls"], "dietary": ["vegetarian"], "allergens": ["dairy", "nuts", "gluten"], "ingredients": ["yogurt", "granola", "berries", "protein powder", "almond butter"], "spice_level": 0, "prep_time_minutes": 5, "preparation_method": ["assembled"], "meal_types": ["breakfast"], "price": 11.99, "calories": 480, "vegetarian_friendly": True, "vegan_friendly": False, "gluten_free": False, "is_signature_dish": False, "is_popular": True, "rating": 4.7, "ai_metadata": {"mood": ["energizing", "satisfying"], "occasion": ["breakfast", "post-workout"], "taste_profile": ["sweet", "creamy"], "texture": ["creamy", "crunchy"]}},
    ]
}

async def generate_embedding(client: AsyncOpenAI, text: str) -> list[float] | None:
    """Generate OpenAI embedding for given text"""
    try:
        response = await client.embeddings.create(
            model=EMBEDDING_MODEL,
            input=text,
            dimensions=EMBEDDING_DIMENSIONS
        )
        return response.data[0].embedding
    except Exception as e:
        print(f"⚠️  Failed to generate embedding: {e}")
        return None


def transform_food_item(food_data: dict, restaurant_id: str, food_index: int) -> dict:
    """Transform raw food data to match FoodItemEntity model"""
    return {
        "food_id": f"food_{restaurant_id}_{food_index}",
        "restaurant_id": restaurant_id,
        "name": food_data["name"],
        "description": food_data["description"],
        "category": food_data["category"],
        "cuisine": food_data["cuisine"],
        "dietary": food_data["dietary"],
        "allergens": food_data["allergens"],
        "ingredients": food_data["ingredients"],
        "spice_level": food_data["spice_level"],
        "prep_time_minutes": food_data.get("prep_time_minutes"),
        "preparation_method": food_data["preparation_method"],
        "meal_types": food_data["meal_types"],
        "price": food_data["price"],
        "calories": food_data.get("calories"),
        "vegetarian_friendly": food_data["vegetarian_friendly"],
        "vegan_friendly": food_data["vegan_friendly"],
        "gluten_free": food_data["gluten_free"],
        "is_signature_dish": food_data["is_signature_dish"],
        "is_popular": food_data["is_popular"],
        "rating": food_data.get("rating"),
        "ai_metadata": food_data["ai_metadata"],
        "created_at": datetime.now(timezone.utc),
        "updated_at": datetime.now(timezone.utc),
    }


async def seed_food(collection) -> list | None:
    """Insert food items, generate embeddings, and create vector search index"""
    all_food_items = []

    print(f"\n📝 Transforming food items...")

    # Transform food items for each restaurant
    for restaurant_id, food_list in FOOD_ITEMS_BY_RESTAURANT.items():
        for idx, food_data in enumerate(food_list, 1):
            transformed = transform_food_item(food_data, restaurant_id, idx)
            all_food_items.append(transformed)

    print(f"📤 Inserting {len(all_food_items)} food items into MongoDB...")
    result = await collection.insert_many(all_food_items)
    print(f"✅ Inserted {len(result.inserted_ids)} food items")

    # Generate embeddings
    if OPENAI_API_KEY:
        print(f"\n🧠 Generating OpenAI embeddings...")
        client = AsyncOpenAI(api_key=OPENAI_API_KEY)

        for i, doc in enumerate(all_food_items, 1):
            try:
                # Use the to_embedding_text method equivalent
                embedding_text = f"{doc['name']}. {doc['description']}. "
                embedding_text += f"Dietary: {', '.join(doc['dietary'])}. "
                embedding_text += f"Category: {doc['category']}. "
                embedding_text += f"Ingredients: {', '.join(doc['ingredients'])}. "

                print(f"   [{i}/{len(all_food_items)}] Embedding: {doc['name']}...")

                vector = await generate_embedding(client, embedding_text)

                if vector:
                    await collection.update_one(
                        {"food_id": doc["food_id"]},
                        {
                            "$set": {
                                "vector_embeddings": vector,
                                "embedding_model": EMBEDDING_MODEL,
                                "embedding_dimensions": EMBEDDING_DIMENSIONS,
                                "embedding_source": embedding_text,
                                "embedding_timestamp": datetime.now(timezone.utc)
                            }
                        }
                    )
                    print(f"      ✅ Embedding stored")

            except Exception as e:
                print(f"      ❌ Error: {e}")

    # Create vector search index
    try:
        print(f"\n📍 Creating vector search index...")
        search_index_model = SearchIndexModel(
            definition={
                "fields": [
                    {
                        "type": "vector",
                        "path": "vector_embeddings",
                        "numDimensions": EMBEDDING_DIMENSIONS,
                        "similarity": "cosine"
                    },
                    {
                        "type": "filter",
                        "path": "restaurant_id"
                    }
                ]
            },
            name="food_vector_index",
            type="vectorSearch"
        )
        await collection.create_search_index(model=search_index_model)
        print(f"✅ Vector search index created")
    except Exception as e:
        print(f"⚠️  Index creation error (may already exist): {e}")

    return all_food_items


async def main():
    """Main function to seed food database"""
    try:
        print("🔌 Connecting to MongoDB...")
        client = AsyncMongoClient(MONGO_URI)
        db = client[DB_NAME]
        collection = db[FOOD_COLLECTION]

        await seed_food(collection)

        print("\n✅ Food seeding completed!")

    except Exception as e:
        print(f"❌ Error: {e}")
    finally:
        await client.close()


if __name__ == "__main__":
    asyncio.run(main())
